name       : dos2unix
version    : 7.3.5
release    : 2
source     :
    - https://waterlan.home.xs4all.nl/dos2unix/dos2unix-7.3.5.tar.gz : a72caa2fb5cb739403315472fe522eda41aabab2a02ad6f5589639330af262e5
license    : BSD-2-Clause-FreeBSD
component  : system.utils
summary    : DOS/Mac to Unix and vice versa text file format converter
description: |
    DOS/Mac to Unix and vice versa text file format converter
build      : |
    %make
install    : |
    %make_install
