name       : dos2unix
version    : 7.5.0
release    : 8
source     :
    - https://download.sourceforge.net/project/dos2unix/dos2unix/7.5.0/dos2unix-7.5.0.tar.gz : 7a3b01d01e214d62c2b3e04c3a92e0ddc728a385566e4c0356efa66fd6eb95af
license    : BSD-2-Clause-FreeBSD
homepage   : https://dos2unix.sourceforge.io/
component  : system.utils
summary    : DOS/Mac to Unix and vice versa text file format converter
description: |
    DOS/Mac to Unix and vice versa text file format converter
build      : |
    %make
install    : |
    %make_install
check      : |
    %make test
