name       : dos2unix
version    : 7.3.4
release    : 1
source     :
    - http://waterlan.home.xs4all.nl/dos2unix/dos2unix-7.3.4.tar.gz : 8ccda7bbc5a2f903dafd95900abb5bf5e77a769b572ef25150fde4056c5f30c5
license    : BSD-2-Clause-FreeBSD
component  : system.utils
summary    : DOS/Mac to Unix and vice versa text file format converter
description: |
    DOS/Mac to Unix and vice versa text file format converter
build      : |
    %make
install    : |
    %make_install
